// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_score_1500_points_in_find_the_stowaway = "CgkIh_T77KUHEAIQCA"; // <GPGSID>
        public const string leaderboard_catch_coins = "CgkIh_T77KUHEAIQAQ"; // <GPGSID>
        public const string leaderboard_find_the_stowaway = "CgkIh_T77KUHEAIQAg"; // <GPGSID>
        public const string achievement_score_500_points_in_find_the_stowaway = "CgkIh_T77KUHEAIQBg"; // <GPGSID>
        public const string achievement_welcome_to_amblio = "CgkIh_T77KUHEAIQAw"; // <GPGSID>
        public const string achievement_try_catch_coins = "CgkIh_T77KUHEAIQBQ"; // <GPGSID>
        public const string achievement_score_1500_points_in_catch_coins = "CgkIh_T77KUHEAIQCw"; // <GPGSID>
        public const string achievement_score_1000_points_in_find_the_stowaway = "CgkIh_T77KUHEAIQBw"; // <GPGSID>
        public const string achievement_score_500_points_in_catch_coins = "CgkIh_T77KUHEAIQCQ"; // <GPGSID>
        public const string achievement_try_find_the_stowaway = "CgkIh_T77KUHEAIQBA"; // <GPGSID>
        public const string achievement_score_1000_points_in_catch_coins = "CgkIh_T77KUHEAIQCg"; // <GPGSID>

}

